-- Account exports are generated by the active private Vercel Blob adapter.
-- Migration 0037 changed the table default, but the original SECURITY DEFINER
-- request function supplied the retired provider explicitly and bypassed it.
CREATE OR REPLACE FUNCTION public.app_request_account_export(
  scoped_idempotency_key text,
  include_source_media boolean,
  export_bucket text
)
RETURNS TABLE (
  job_id uuid,
  job_status public.export_job_status,
  replayed boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
  actor uuid := public.app_actor_id();
  selected_job public.export_jobs%ROWTYPE;
  new_job_id uuid := gen_random_uuid();
  new_asset_id uuid := gen_random_uuid();
BEGIN
  IF actor IS NULL
    OR scoped_idempotency_key IS NULL
    OR scoped_idempotency_key !~ '^[0-9a-f]{64}$'
    OR include_source_media IS NULL
    OR export_bucket IS NULL
    OR export_bucket !~ '^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$' THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'invalid account export request';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended('account-export:' || actor::text, 0));
  PERFORM 1
  FROM public.app_users account
  WHERE account.id = actor
    AND account.status = 'active'
    AND account.deleted_at IS NULL
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'account is not active';
  END IF;

  SELECT job.* INTO selected_job
  FROM public.export_jobs job
  WHERE job.user_id = actor
    AND job.idempotency_key = scoped_idempotency_key
  LIMIT 1;
  IF FOUND THEN
    RETURN QUERY SELECT selected_job.id, selected_job.status, true;
    RETURN;
  END IF;

  SELECT job.* INTO selected_job
  FROM public.export_jobs job
  WHERE job.user_id = actor
    AND job.status IN ('requested', 'processing', 'retry_scheduled')
  ORDER BY job.created_at DESC, job.id DESC
  LIMIT 1
  FOR UPDATE;
  IF FOUND THEN
    RETURN QUERY SELECT selected_job.id, selected_job.status, true;
    RETURN;
  END IF;

  INSERT INTO public.media_assets (
    id, owner_id, project_id, purpose, status, storage_provider, bucket,
    object_key, upload_idempotency_key, claimed_content_type, exif_stripped,
    is_current
  ) VALUES (
    new_asset_id, actor, NULL, 'export_archive', 'processing', 'vercel_blob', export_bucket,
    'exports/' || left(new_asset_id::text, 2) || '/' || new_asset_id::text || '/buildy-export.zip',
    'account-export:v1:' || new_job_id::text,
    'application/zip', false, true
  );

  INSERT INTO public.export_jobs (
    id, user_id, idempotency_key, status, format, include_media,
    export_asset_id, available_at
  ) VALUES (
    new_job_id, actor, scoped_idempotency_key, 'requested', 'zip',
    include_source_media, new_asset_id, statement_timestamp()
  ) RETURNING * INTO selected_job;

  INSERT INTO public.audit_events (
    actor_kind, actor_user_id, action, resource_type, resource_id, metadata
  ) VALUES (
    'user', actor, 'account.export_requested', 'export_job', selected_job.id,
    jsonb_build_object('schemaVersion', 1, 'includeMedia', include_source_media)
  );

  RETURN QUERY SELECT selected_job.id, selected_job.status, false;
END
$function$;

REVOKE ALL ON FUNCTION public.app_request_account_export(text, boolean, text) FROM PUBLIC;
