import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { appUsers } from "./auth.js";
import {
  fulfilmentStatusEnum,
  optimisticVersion,
  paymentStatusEnum,
  photobookDraftStatusEnum,
  photobookExclusionTargetEnum,
  photobookOrderStatusEnum,
  photobookProofStatusEnum,
  timestamps,
} from "./common.js";
import { mediaAssets } from "./media.js";
import { projects, updates } from "./projects.js";
import type { PhotobookDocument } from "../../shared/contracts/photobooks.js";

export const photobookDrafts = pgTable(
  "photobook_drafts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    ownerId: uuid("owner_id").notNull(),
    status: photobookDraftStatusEnum("status").default("draft").notNull(),
    schemaVersion: integer("schema_version").default(1).notNull(),
    projectRevision: bigint("project_revision", { mode: "number" }).notNull(),
    document: jsonb("document").$type<PhotobookDocument>().notNull(),
    documentSha256: text("document_sha256"),
    pageCount: integer("page_count"),
    selectedFormat: text("selected_format").default("a4-landscape-hardcover-v1").notNull(),
    version: optimisticVersion(),
    ...timestamps(),
  },
  (table) => [
    foreignKey({
      name: "photobook_drafts_project_owner_fk",
      columns: [table.projectId, table.ownerId],
      foreignColumns: [projects.id, projects.ownerId],
    }).onDelete("cascade"),
    uniqueIndex("photobook_drafts_project_uq").on(table.projectId),
    unique("photobook_drafts_id_project_uq").on(table.id, table.projectId),
    index("photobook_drafts_owner_status_idx").on(table.ownerId, table.status, table.updatedAt),
    check("photobook_drafts_schema_revision_ck", sql`${table.schemaVersion} > 0 AND ${table.projectRevision} > 0 AND ${table.version} > 0`),
    check("photobook_drafts_document_object_ck", sql`jsonb_typeof(${table.document}) = 'object'`),
    check("photobook_drafts_document_sha_ck", sql`${table.documentSha256} IS NULL OR ${table.documentSha256} ~ '^[0-9a-f]{64}$'`),
    check("photobook_drafts_page_count_ck", sql`${table.pageCount} IS NULL OR ${table.pageCount} > 0`),
    check("photobook_drafts_format_ck", sql`char_length(btrim(${table.selectedFormat})) BETWEEN 1 AND 80`),
  ],
);

export const photobookSettings = pgTable(
  "photobook_settings",
  {
    projectId: uuid("project_id").primaryKey(),
    ownerId: uuid("owner_id").notNull(),
    coverMediaAssetId: uuid("cover_media_asset_id"),
    selectedFormat: text("selected_format").default("a4-landscape-hardcover-v1").notNull(),
    title: text("title"),
    subtitle: text("subtitle"),
    includeBudget: boolean("include_budget").default(false).notNull(),
    preferences: jsonb("preferences").$type<Record<string, unknown>>().default({}).notNull(),
    version: optimisticVersion(),
    ...timestamps(),
  },
  (table) => [
    foreignKey({
      name: "photobook_settings_project_owner_fk",
      columns: [table.projectId, table.ownerId],
      foreignColumns: [projects.id, projects.ownerId],
    }).onDelete("cascade"),
    foreignKey({
      name: "photobook_settings_cover_project_fk",
      columns: [table.coverMediaAssetId, table.projectId],
      foreignColumns: [mediaAssets.id, mediaAssets.projectId],
    }).onDelete("restrict"),
    check("photobook_settings_title_ck", sql`${table.title} IS NULL OR char_length(${table.title}) <= 160`),
    check("photobook_settings_subtitle_ck", sql`${table.subtitle} IS NULL OR char_length(${table.subtitle}) <= 240`),
    check("photobook_settings_preferences_ck", sql`jsonb_typeof(${table.preferences}) = 'object'`),
    check("photobook_settings_version_ck", sql`${table.version} > 0`),
  ],
);

export const photobookExclusions = pgTable(
  "photobook_exclusions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    draftId: uuid("draft_id").notNull(),
    projectId: uuid("project_id").notNull(),
    targetType: photobookExclusionTargetEnum("target_type").notNull(),
    updateId: uuid("update_id"),
    mediaAssetId: uuid("media_asset_id"),
    chapterKey: text("chapter_key"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    foreignKey({
      name: "photobook_exclusions_draft_project_fk",
      columns: [table.draftId, table.projectId],
      foreignColumns: [photobookDrafts.id, photobookDrafts.projectId],
    }).onDelete("cascade"),
    foreignKey({
      name: "photobook_exclusions_update_project_fk",
      columns: [table.updateId, table.projectId],
      foreignColumns: [updates.id, updates.projectId],
    }).onDelete("cascade"),
    foreignKey({
      name: "photobook_exclusions_media_project_fk",
      columns: [table.mediaAssetId, table.projectId],
      foreignColumns: [mediaAssets.id, mediaAssets.projectId],
    }).onDelete("cascade"),
    uniqueIndex("photobook_exclusions_target_uq").on(
      table.draftId,
      table.targetType,
      sql`coalesce(${table.updateId}, '00000000-0000-0000-0000-000000000000'::uuid)`,
      sql`coalesce(${table.mediaAssetId}, '00000000-0000-0000-0000-000000000000'::uuid)`,
      sql`coalesce(${table.chapterKey}, '')`,
    ),
    index("photobook_exclusions_project_idx").on(table.projectId, table.draftId),
    check(
      "photobook_exclusions_shape_ck",
      sql`(${table.targetType} = 'update' AND ${table.updateId} IS NOT NULL AND ${table.mediaAssetId} IS NULL AND ${table.chapterKey} IS NULL) OR (${table.targetType} = 'media' AND ${table.updateId} IS NULL AND ${table.mediaAssetId} IS NOT NULL AND ${table.chapterKey} IS NULL) OR (${table.targetType} = 'chapter' AND ${table.updateId} IS NULL AND ${table.mediaAssetId} IS NULL AND ${table.chapterKey} IS NOT NULL AND char_length(btrim(${table.chapterKey})) > 0)`,
    ),
  ],
);

export const photobookRevisions = pgTable(
  "photobook_revisions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    draftId: uuid("draft_id").notNull(),
    projectId: uuid("project_id").notNull(),
    ownerId: uuid("owner_id").notNull(),
    revisionNumber: integer("revision_number").notNull(),
    status: photobookProofStatusEnum("status").default("draft").notNull(),
    schemaVersion: integer("schema_version").notNull(),
    projectRevision: bigint("project_revision", { mode: "number" }).notNull(),
    document: jsonb("document").$type<PhotobookDocument>().notNull(),
    documentSha256: text("document_sha256").notNull(),
    assetSet: jsonb("asset_set").$type<Array<{ id: string; sha256: string }>>().notNull(),
    assetSetSha256: text("asset_set_sha256").notNull(),
    pdfAssetId: uuid("pdf_asset_id"),
    pdfSha256: text("pdf_sha256"),
    pdfSizeBytes: bigint("pdf_size_bytes", { mode: "number" }),
    pageCount: integer("page_count"),
    renderEngine: text("render_engine").notNull(),
    renderVersion: text("render_version").notNull(),
    fontSetSha256: text("font_set_sha256"),
    approvedById: uuid("approved_by_id").references(() => appUsers.id, { onDelete: "restrict" }),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    lockedAt: timestamp("locked_at", { withTimezone: true }),
    invalidatedAt: timestamp("invalidated_at", { withTimezone: true }),
    invalidationReason: text("invalidation_reason"),
    failureCode: text("failure_code"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    foreignKey({
      name: "photobook_revisions_draft_project_fk",
      columns: [table.draftId, table.projectId],
      foreignColumns: [photobookDrafts.id, photobookDrafts.projectId],
    }).onDelete("restrict"),
    foreignKey({
      name: "photobook_revisions_project_owner_fk",
      columns: [table.projectId, table.ownerId],
      foreignColumns: [projects.id, projects.ownerId],
    }).onDelete("restrict"),
    foreignKey({
      name: "photobook_revisions_pdf_project_fk",
      columns: [table.pdfAssetId, table.projectId],
      foreignColumns: [mediaAssets.id, mediaAssets.projectId],
    }).onDelete("restrict"),
    unique("photobook_revisions_id_project_uq").on(table.id, table.projectId),
    uniqueIndex("photobook_revisions_draft_number_uq").on(table.draftId, table.revisionNumber),
    uniqueIndex("photobook_revisions_pdf_asset_uq").on(table.pdfAssetId),
    index("photobook_revisions_project_status_idx").on(table.projectId, table.status, table.createdAt),
    check("photobook_revisions_number_ck", sql`${table.revisionNumber} > 0 AND ${table.schemaVersion} > 0 AND ${table.projectRevision} > 0`),
    check("photobook_revisions_document_ck", sql`jsonb_typeof(${table.document}) = 'object' AND jsonb_typeof(${table.assetSet}) = 'array'`),
    check("photobook_revisions_hashes_ck", sql`${table.documentSha256} ~ '^[0-9a-f]{64}$' AND ${table.assetSetSha256} ~ '^[0-9a-f]{64}$' AND (${table.pdfSha256} IS NULL OR ${table.pdfSha256} ~ '^[0-9a-f]{64}$')`),
    check("photobook_revisions_font_hash_ck", sql`${table.fontSetSha256} IS NULL OR ${table.fontSetSha256} ~ '^[0-9a-f]{64}$'`),
    check("photobook_revisions_pdf_size_ck", sql`${table.pdfSizeBytes} IS NULL OR ${table.pdfSizeBytes} > 0`),
    check(
      "photobook_revisions_ready_proof_ck",
      sql`${table.status} NOT IN ('ready', 'approved', 'locked') OR (${table.pdfAssetId} IS NOT NULL AND ${table.pdfSha256} IS NOT NULL AND ${table.pdfSizeBytes} IS NOT NULL AND ${table.pageCount} IS NOT NULL AND ${table.fontSetSha256} IS NOT NULL AND ${table.pageCount} >= 24 AND mod(${table.pageCount}, 2) = 0)`,
    ),
    check(
      "photobook_revisions_approval_ck",
      sql`${table.status} NOT IN ('approved', 'locked') OR (${table.approvedById} IS NOT NULL AND ${table.approvedById} = ${table.ownerId} AND ${table.approvedAt} IS NOT NULL)`,
    ),
    check(
      "photobook_revisions_lock_ck",
      sql`${table.status} <> 'locked' OR ${table.lockedAt} IS NOT NULL`,
    ),
    check(
      "photobook_revisions_invalidation_ck",
      sql`${table.status} <> 'invalidated' OR (${table.invalidatedAt} IS NOT NULL AND ${table.invalidationReason} IS NOT NULL AND char_length(btrim(${table.invalidationReason})) > 0)`,
    ),
  ],
);

export const photobookOrders = pgTable(
  "photobook_orders",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    orderNumber: text("order_number").notNull(),
    merchantReference: text("merchant_reference").notNull(),
    projectId: uuid("project_id").notNull(),
    ownerId: uuid("owner_id").notNull(),
    proofRevisionId: uuid("proof_revision_id").notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    status: photobookOrderStatusEnum("status").default("draft").notNull(),
    paymentStatus: paymentStatusEnum("payment_status").default("unpaid").notNull(),
    fulfilmentStatus: fulfilmentStatusEnum("fulfilment_status").default("unclaimed").notNull(),
    currency: text("currency").notNull(),
    quantity: integer("quantity").default(1).notNull(),
    subtotalMinor: integer("subtotal_minor").notNull(),
    shippingMinor: integer("shipping_minor").notNull(),
    taxMinor: integer("tax_minor").notNull(),
    totalMinor: integer("total_minor").notNull(),
    shippingCountry: text("shipping_country").notNull(),
    customerEmailCiphertext: text("customer_email_ciphertext"),
    shippingDetailsCiphertext: text("shipping_details_ciphertext"),
    piiEncryptionKeyVersion: integer("pii_encryption_key_version").default(1).notNull(),
    checkoutSnapshot: jsonb("checkout_snapshot").$type<Record<string, unknown>>().notNull(),
    sellerSnapshot: jsonb("seller_snapshot").$type<Record<string, unknown>>().notNull(),
    termsVersion: text("terms_version").notNull(),
    legalAcceptedAt: timestamp("legal_accepted_at", { withTimezone: true }).notNull(),
    stripeCheckoutSessionId: text("stripe_checkout_session_id"),
    stripeCheckoutExpiresAt: timestamp("stripe_checkout_expires_at", { withTimezone: true }),
    stripePaymentIntentId: text("stripe_payment_intent_id"),
    stripeChargeId: text("stripe_charge_id"),
    refundedMinor: integer("refunded_minor").default(0).notNull(),
    peechoOrderId: text("peecho_order_id"),
    peechoEnvironment: text("peecho_environment"),
    peechoStatus: text("peecho_status"),
    peechoCreateStartedAt: timestamp("peecho_create_started_at", { withTimezone: true }),
    peechoPaymentStartedAt: timestamp("peecho_payment_started_at", { withTimezone: true }),
    peechoSubmittedAt: timestamp("peecho_submitted_at", { withTimezone: true }),
    peechoLastStatusAt: timestamp("peecho_last_status_at", { withTimezone: true }),
    deliveryEstimate: text("delivery_estimate"),
    trackingCode: text("tracking_code"),
    trackingUrl: text("tracking_url"),
    fulfilmentLeaseOwner: text("fulfilment_lease_owner"),
    fulfilmentLeaseExpiresAt: timestamp("fulfilment_lease_expires_at", { withTimezone: true }),
    retryCount: integer("retry_count").default(0).notNull(),
    nextRetryAt: timestamp("next_retry_at", { withTimezone: true }),
    fulfilmentDeadLetteredAt: timestamp("fulfilment_dead_lettered_at", { withTimezone: true }),
    lastErrorCode: text("last_error_code"),
    paidAt: timestamp("paid_at", { withTimezone: true }),
    version: optimisticVersion(),
    ...timestamps(),
  },
  (table) => [
    foreignKey({
      name: "photobook_orders_project_owner_fk",
      columns: [table.projectId, table.ownerId],
      foreignColumns: [projects.id, projects.ownerId],
    }).onDelete("restrict"),
    foreignKey({
      name: "photobook_orders_proof_project_fk",
      columns: [table.proofRevisionId, table.projectId],
      foreignColumns: [photobookRevisions.id, photobookRevisions.projectId],
    }).onDelete("restrict"),
    uniqueIndex("photobook_orders_order_number_uq").on(table.orderNumber),
    uniqueIndex("photobook_orders_merchant_reference_uq").on(table.merchantReference),
    uniqueIndex("photobook_orders_idempotency_uq").on(table.idempotencyKey),
    uniqueIndex("photobook_orders_proof_revision_uq").on(table.proofRevisionId),
    uniqueIndex("photobook_orders_stripe_session_uq").on(table.stripeCheckoutSessionId),
    uniqueIndex("photobook_orders_stripe_intent_uq").on(table.stripePaymentIntentId),
    uniqueIndex("photobook_orders_stripe_charge_uq").on(table.stripeChargeId),
    uniqueIndex("photobook_orders_peecho_order_uq").on(table.peechoOrderId),
    index("photobook_orders_owner_created_idx").on(table.ownerId, table.createdAt),
    index("photobook_orders_fulfilment_queue_idx").on(table.fulfilmentStatus, table.nextRetryAt),
    index("photobook_orders_peecho_paid_queue_idx")
      .on(table.nextRetryAt, table.fulfilmentLeaseExpiresAt, table.createdAt)
      .where(sql`${table.status} = 'paid' AND ${table.paymentStatus} = 'paid' AND ${table.fulfilmentStatus} IN ('unclaimed', 'claimed', 'peecho_order_created', 'peecho_payment_pending', 'retry_scheduled') AND ${table.fulfilmentDeadLetteredAt} IS NULL`),
    check("photobook_orders_number_ck", sql`${table.orderNumber} ~ '^BLD-[A-Z0-9-]{8,40}$'`),
    check("photobook_orders_reference_ck", sql`char_length(${table.merchantReference}) BETWEEN 8 AND 100`),
    check("photobook_orders_currency_country_ck", sql`${table.currency} ~ '^[A-Z]{3}$' AND ${table.shippingCountry} ~ '^[A-Z]{2}$'`),
    check("photobook_orders_amounts_ck", sql`${table.quantity} > 0 AND ${table.subtotalMinor} >= 0 AND ${table.shippingMinor} >= 0 AND ${table.taxMinor} >= 0 AND ${table.totalMinor} = ${table.subtotalMinor} + ${table.shippingMinor} + ${table.taxMinor}`),
    check("photobook_orders_snapshots_ck", sql`jsonb_typeof(${table.checkoutSnapshot}) = 'object' AND jsonb_typeof(${table.sellerSnapshot}) = 'object'`),
    check("photobook_orders_lease_ck", sql`(${table.fulfilmentLeaseOwner} IS NULL) = (${table.fulfilmentLeaseExpiresAt} IS NULL)`),
    check("photobook_orders_retry_version_ck", sql`${table.retryCount} >= 0 AND ${table.piiEncryptionKeyVersion} > 0 AND ${table.version} > 0`),
    check("photobook_orders_paid_ck", sql`${table.paymentStatus} NOT IN ('paid', 'partially_refunded', 'refunded') OR ${table.paidAt} IS NOT NULL`),
    check("photobook_orders_stripe_charge_ck", sql`${table.stripeChargeId} IS NULL OR ${table.stripeChargeId} ~ '^ch_[A-Za-z0-9_]{3,250}$'`),
    check("photobook_orders_peecho_environment_ck", sql`${table.peechoEnvironment} IS NULL OR ${table.peechoEnvironment} IN ('test', 'live')`),
    check("photobook_orders_peecho_id_ck", sql`${table.peechoOrderId} IS NULL OR ${table.peechoOrderId} ~ '^[1-9][0-9]{0,15}$'`),
    check("photobook_orders_peecho_status_ck", sql`${table.peechoStatus} IS NULL OR ${table.peechoStatus} ~ '^[A-Z][A-Z0-9_]{0,79}$'`),
    check("photobook_orders_peecho_identity_ck", sql`${table.peechoOrderId} IS NULL OR (${table.peechoEnvironment} IS NOT NULL AND ${table.peechoCreateStartedAt} IS NOT NULL)`),
    check("photobook_orders_peecho_payment_ck", sql`${table.peechoPaymentStartedAt} IS NULL OR ${table.peechoOrderId} IS NOT NULL`),
    check("photobook_orders_peecho_submission_ck", sql`${table.peechoSubmittedAt} IS NULL OR ${table.peechoOrderId} IS NOT NULL`),
    check("photobook_orders_tracking_code_ck", sql`${table.trackingCode} IS NULL OR char_length(${table.trackingCode}) BETWEEN 1 AND 500`),
    check("photobook_orders_fulfilment_dead_letter_ck", sql`${table.fulfilmentDeadLetteredAt} IS NULL OR (${table.fulfilmentStatus} = 'manual_review' AND ${table.status} = 'manual_review')`),
    check(
      "photobook_orders_refund_amount_ck",
      sql`${table.refundedMinor} >= 0 AND ${table.refundedMinor} <= ${table.totalMinor} AND ((${table.paymentStatus} = 'partially_refunded' AND ${table.refundedMinor} > 0 AND ${table.refundedMinor} < ${table.totalMinor}) OR (${table.paymentStatus} = 'refunded' AND ${table.refundedMinor} = ${table.totalMinor}) OR (${table.paymentStatus} NOT IN ('partially_refunded', 'refunded') AND ${table.refundedMinor} = 0))`,
    ),
    check(
      "photobook_orders_checkout_session_ck",
      sql`(${table.stripeCheckoutSessionId} IS NULL) = (${table.stripeCheckoutExpiresAt} IS NULL)`,
    ),
    check(
      "photobook_orders_tracking_url_ck",
      sql`${table.trackingUrl} IS NULL OR ${table.trackingUrl} ~ '^https://'`,
    ),
  ],
);

export const photobookOrderEvents = pgTable(
  "photobook_order_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    orderId: uuid("order_id")
      .notNull()
      .references(() => photobookOrders.id, { onDelete: "restrict" }),
    source: text("source").notNull(),
    eventType: text("event_type").notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    providerEventId: text("provider_event_id"),
    actorUserId: uuid("actor_user_id").references(() => appUsers.id, { onDelete: "set null" }),
    fromStatus: text("from_status"),
    toStatus: text("to_status"),
    payloadSummary: jsonb("payload_summary").$type<Record<string, unknown>>().default({}).notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("photobook_order_events_idempotency_uq").on(table.idempotencyKey),
    index("photobook_order_events_order_time_idx").on(table.orderId, table.occurredAt),
    index("photobook_order_events_provider_idx").on(table.source, table.providerEventId),
    check("photobook_order_events_source_ck", sql`${table.source} IN ('user', 'system', 'stripe', 'peecho', 'admin')`),
    check("photobook_order_events_type_ck", sql`char_length(btrim(${table.eventType})) BETWEEN 1 AND 100`),
    check("photobook_order_events_payload_ck", sql`jsonb_typeof(${table.payloadSummary}) = 'object'`),
  ],
);
